---
- name: host > os family - distro - release - version
  command: >
    echo "{{ item }}"
  with_items:
    - "{{ ansible_os_family }} - {{ ansible_distribution }} - {{
      ansible_distribution_release }} - {{ ansible_distribution_major_version }}"
  changed_when: false

- name: run compatibility tests
  include_tasks: "compat.yml"

- name: include source vars
  include_vars: "source.yml"

- name: include os vars
  include_vars: "os/{{ ansible_distribution }}.yml"

- name: check current installation
  register: __current_apr
  shell: >
    {{ cmd_apr_version }}
  changed_when: false

- name: compare version with current one
  set_fact:
    __install_apr: "{% if __current_apr is failed %}false{% elif __current_apr.stdout == 'NaN' %}true{%
      else %}false{% endif %}"
    __upgrade_apr: "{% if __current_apr is failed %}false{% elif __current_apr.stdout == 'NaN' %}false{%
      else %}{{ __current_apr.stdout is version(apr_source_version, '<', strict=true) }}{% endif %}"

- name: force compile = {{ apr_force_compile }}
  set_fact:
    __install_apr: true
    __upgrade_apr: true
  when: apr_force_compile

- block:
    - include_role:
        name: common
        tasks_from: package
      vars:
        packages_present: "{{ os_packages_present }}"
        packages_absent: "{{ os_packages_absent }}"
        update_cache: true
        dnf_via_shell: true
        print_list: true

    # apr
    - include_role:
        name: common
        tasks_from: url-tgz
      vars:
        source: "{{ apr_source_name }}"
        source_src: "{{ apr_source_src }}"
        source_tgz: "{{ apr_source_tgz }}"
        source_dir: "{{ apr_source_dir }}"

    - name: buildconf
      command: >
        ./buildconf
      args:
        chdir: "{{ apr_source_dir }}"

    - name: configure
      command: >
        ./configure \
          --prefix="{{ apr_target_dir }}" \
          --exec-prefix="{{ apr_target_dir }}"
      args:
        chdir: "{{ apr_source_dir }}"

    - name: compile
      make:
        chdir: "{{ apr_source_dir }}"

    - name: install
      make:
        chdir: "{{ apr_source_dir }}"
        target: install

    # shell only
    - name: linkig bin, lib
      shell: >
        ln -sf {{ apr_target_dir }}/bin/apr-1-config -T {{ os_bin_path }}/apr-1-config;
      args:
        warn: false

    - name: configure ldconfig file
      template:
        src: apr.j2
        dest: "{{ ldconfig_config_path }}/apr.conf"
        mode: 0644
        owner: root
        group: root

    - name: rebuild ldconfig cache
      shell: >
        rm -rf {{ ldconfig_cache_path }}; ldconfig
      args:
        warn: false
  when: __install_apr or __upgrade_apr

- name: clean-up
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ apr_source_dir }}"

- name: validate version
  register: __validate_apr_version
  shell: >
    {{ cmd_apr_version }}
  changed_when: false

- name: validate libs
  register: __validate_apr_libs
  shell: >
    ldconfig -p | grep apr
  changed_when: false

- name: results
  command: >
    echo "{{ item }}"
  with_items:
    - "{{ apr_target_exec }} version is {{ __validate_apr_version.stdout }}"
    - "{{ __validate_apr_libs.stdout }}"
  changed_when: false
