---
apr_util_dependencies:
  Debian:
  # essentials
  - aptitude
  - autoconf
  - automake
  - autotools-dev
  - build-essential
  - libtool
  - libtool-bin
  - libldap2-dev
  - libssl-dev
  - libsqlite3-dev
  - libdb-dev
  - libexpat-dev
  - libxml2-dev
