---
- name: install dependency packages...
  package: 
    name: "{{ mariadb_dependency }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ mariadb_dependencies[ansible_distribution] }}"
  loop_control:
      loop_var: mariadb_dependency

- pip:
    name: "{{ mariadb_pip_package }}"
    state: present
  with_items: "{{ mariadb_pip_packages }}"
  loop_control:
      loop_var: mariadb_pip_package
