---
galaxy_info:
  author: Fatih Piristine
  description: Ansible role to compile Apache APR-iconv.
  company: Hexon
  license: Apache
  min_ansible_version: 2.7
  platforms:
    - name: CentOS
      versions:
        - 7
        - 6
    - name: Debian
      versions:
        - stretch
        - jessie
        - wheezy
    - name: Fedora
      versions:
        - 30
        - 29
        - 28
        - 27
        - 26
        - 25
    - name: Ubuntu
      versions:
        - bionic
        - xenial
        - trusty
        - precise
  categories:
    - utility
dependencies:
  - common
  - apr
