---
source_openssl_name: "openssl"
# source_openssl_version: "1.1.0h" # must be defined in role

source_openssl_name_full: "{{ source_openssl_name }}-{{ source_openssl_version }}"
source_openssl_name_tar: "{{ source_openssl_name_full }}.tar.gz"

source_openssl_src: "https://www.openssl.org/source/{{ source_openssl_name_tar }}"
source_openssl_tgz: "/tmp/{{ source_openssl_name_tar }}"
source_openssl_dir: "/tmp/{{ source_openssl_name }}"

target_openssl_dir: "/opt/{{ source_openssl_name }}"
target_openssl_exec: "{{ target_openssl_dir }}/bin/openssl"
target_openssl_exec_version: "{{ target_openssl_exec }} --version"