---
source_pcre_name: "pcre"
# source_pcre_version: "8.42" # must be defined in role

source_pcre_name_full: "{{ source_pcre_name }}-{{ source_pcre_version }}"
source_pcre_name_tar: "{{ source_pcre_name_full }}.tar.gz"

source_pcre_src: "https://ftp.pcre.org/pub/pcre/{{ source_pcre_name_tar }}"
source_pcre_tgz: "/tmp/{{ source_pcre_name_tar }}"
source_pcre_dir: "/tmp/{{ source_pcre_name }}"

target_pcre_dir: "/opt/{{ source_pcre_name }}"
target_pcre_exec: "{{ target_pcre_dir }}/bin/pcre"
target_pcre_exec_version: "{{ target_pcre_exec }} --version"