---
source_php_name: "php"
# source_php_version: "7.2.5" # must be defined in role

source_php_name_full: "{{ source_php_name }}-{{ source_php_version }}"
source_php_name_tar: "{{ source_php_name_full }}.tar.gz"

source_php_src: "http://fi2.php.net/get/{{ source_php_name_tar }}/from/this/mirror"
source_php_tgz: "/tmp/{{ source_php_name_tar }}"
source_php_dir: "/tmp/{{ source_php_name }}"

target_php_dir: "/opt/{{ source_php_name }}"
target_php_exec: "{{ target_php_dir }}/bin/php"
target_php_exec_version: "{{ target_php_exec }} -i | grep -m1 'PHP Version =>'"
