---
galaxy_info:
  author: Fatih Piristine
  description: Shared tasks and vars between roles.
  company: Hexon
  license: Apache
  min_ansible_version: 2.5
  platforms:
  - name: EL
    versions:
    - all
  - name: GenericUNIX
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: opensuse
    versions:
    - all
  - name: Amazon
    versions:
    - all
  - name: GenericBSD
    versions:
    - all
  - name: FreeBSD
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: SLES
    versions:
    - all
  - name: GenericLinux
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - system
  - configuration
dependencies: []
