---
- name: host > os family - distro - release - version
  command: >
    echo "{{ item }}"
  with_items:
    - "{{ ansible_os_family }} - {{ ansible_distribution }} - {{
      ansible_distribution_release }} - {{ ansible_distribution_major_version }}"
  changed_when: false

- name: run compatibility tests
  include_tasks: "compat.yml"

- name: include source vars
  include_vars: "source.yml"

- name: include os vars
  include_vars: "os/{{ ansible_distribution }}.yml"

- name: check current installation
  register: __current_apr_util
  shell: >
    {{ cmd_apr_util_version }}
  changed_when: false

- name: compare version with current one
  set_fact:
    __install_apr_util: "{% if __current_apr_util is failed %}false{% elif __current_apr_util.stdout == 'NaN'
      %}true{% else %}false{% endif %}"
    __upgrade_apr_util: "{% if __current_apr_util is failed %}false{% elif __current_apr_util.stdout == 'NaN'
      %}false{% else %}{{ __current_apr_util.stdout is version(apr_util_source_version, '<', strict=true)
      }}{% endif %}"

- name: force compile = {{ apr_util_force_compile }}
  set_fact:
    __install_apr_util: true
    __upgrade_apr_util: true
  when: apr_util_force_compile

- block:
    - name: include vars from apr
      include_role:
        name: apr
        vars_from: "source.yml"
        public: true

    - name: include vars from apr-iconv
      include_role:
        name: apr-iconv
        vars_from: "source.yml"
        public: true

    - include_role:
        name: common
        tasks_from: package
      vars:
        packages_present: "{{ os_packages_present }}"
        packages_absent: "{{ os_packages_absent }}"
        update_cache: true
        dnf_via_shell: true
        print_list: true

    # apr
    - include_role:
        name: common
        tasks_from: url-tgz
      vars:
        source: "{{ apr_source_name }}"
        source_src: "{{ apr_source_src }}"
        source_tgz: "{{ apr_source_tgz }}"
        source_dir: "{{ apr_source_dir }}"

    # apr-util
    - include_role:
        name: common
        tasks_from: url-tgz
      vars:
        source: "{{ apr_util_source_name }}"
        source_src: "{{ apr_util_source_src }}"
        source_tgz: "{{ apr_util_source_tgz }}"
        source_dir: "{{ apr_util_source_dir }}"

    - name: buildconf
      command: >
        ./buildconf \
          --with-apr="{{ apr_source_dir }}"
      args:
        chdir: "{{ apr_util_source_dir }}"

    - name: configure
      command: >
        ./configure \
          --prefix="{{ apr_util_target_dir }}" \
          --exec-prefix="{{ apr_util_target_dir }}" \
          --with-apr="{{ apr_target_exec }}" \
          --with-apr-iconv="{{ apr_iconv_target_exec }}" \
          --with-expat=/usr/lib \
          --with-crypto \
          --with-berkeley-db \
          --with-openssl=/usr/include \
          --with-sqlite3=/usr/include \
          --with-ldap-include=/usr/include \
          --with-mysql=/usr/include/mysql \
          --with-pgsql=/usr/include/postgresql \
          --with-iconv="{{ apr_iconv_target_dir }}"
      args:
        chdir: "{{ apr_util_source_dir }}"

    - name: compile
      make:
        chdir: "{{ apr_util_source_dir }}"

    - name: install
      make:
        chdir: "{{ apr_util_source_dir }}"
        target: install

    # shell only
    - name: linkig bin, lib
      shell: >
        ln -sf {{ apr_util_target_dir }}/bin/apu-1-config -T {{ os_bin_path }}/apu-1-config;
      args:
        warn: false

    - name: configure ldconfig file
      template:
        src: apr-util.j2
        dest: "{{ ldconfig_config_path }}/apr-util.conf"
        mode: 0644
        owner: root
        group: root

    - name: rebuild ldconfig cache
      shell: >
        rm -rf {{ ldconfig_cache_path }}; ldconfig
      args:
        warn: false
  when: __install_apr_util or __upgrade_apr_util

- name: clean-up
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ apr_source_dir }}"
    - "{{ apr_iconv_source_dir }}"
    - "{{ apr_util_source_dir }}"

- name: validate installation
  register: __validate_apr_util
  shell: >
    {{ cmd_apr_util_version }}
  changed_when: false

- name: validate libs
  register: __validate_apr_util_libs
  shell: >
    ldconfig -p | grep apr
  changed_when: false

- name: results
  command: >
    echo "{{ item }}"
  with_items:
    - "{{ apr_util_target_exec }} version is {{ __validate_apr_util.stdout }}"
    - "{{ __validate_apr_util_libs.stdout }}"
  changed_when: false
