---
- name: host > os family - distro - release - version
  command: >
    echo "{{ item }}"
  with_items:
    - "{{ ansible_os_family }} - {{ ansible_distribution }} - {{
      ansible_distribution_release }} - {{ ansible_distribution_major_version }}"
  changed_when: false

- name: determine executable path
  command: which wkhtmltopdf
  register: __executable
  changed_when: false
  failed_when: false

- set_fact:
    wkhtmltox_exec: "{{ __executable.stdout }}"
  when: __executable.rc == 0

- name: check current installation
  register: __current
  shell: >
    {{ cmd_wkhtmltox_version }}
  changed_when: false

- include_tasks: deb.yml
  when: wkhtmltox_package_type == 'deb'

- include_tasks: tgz.yml
  when: wkhtmltox_package_type == 'tgz'

- name: validate installation
  register: __validate
  shell: >
    {{ cmd_wkhtmltox_version }}
  changed_when: false

- name: results
  command: >
    echo "{{ item }}"
  with_items:
    - "wkhtmltopdf version is {{ __validate.stdout }}"
  changed_when: false
