---
- name: compare version with current one
  set_fact:
    __app_install: "{% if __app_current is failed %}False{% elif __app_current.stdout == 'Install' %}True{% else %}{{ __app_current.stdout is version(wkhtmltox_tgz_version, '<', strict=True) }}{% endif %}"

- set_fact:
    __app_install: true
  when: wkhtmltox_force_purge

- name: delete existing installation
  file:
    path: "{{ wkhtmltox_tgz_dir }}"
    state: absent
  when: __app_install

- name: create working directory
  file:
    path: "{{ wkhtmltox_tgz_dir }}"
    mode: 0755
    state: directory
  when: __app_install

- name: download wkhtmltox package
  get_url:
    url: "{{ wkhtmltox_tgz_url }}"
    dest: "{{ wkhtmltox_tgz_dst }}"
  when: __app_install

- name: unpack tar package
  unarchive:
    src: "{{ wkhtmltox_tgz_dst }}"
    dest: "{{ wkhtmltox_tgz_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: __app_install

- name: apply file permissions
  file:
    dest: "{{ wkhtmltox_tgz_dir }}"
    owner: root
    group: root
    recurse: yes
  when: __app_install

- name: clean-up
  file:
    path: "{{ wkhtmltox_tgz_dst }}"
    state: absent

- name: purge current installation packages (apt)...
  apt:
    name: "{{ wkhtmltox_dpkg_name }}"
    state: absent
    update_cache: yes
    cache_valid_time: 3600
    purge: yes
  when: __app_install

- name: purge current installation packages (dpkg)...
  shell: >
    dpkg --purge {{ wkhtmltox_dpkg_name }}
  when: __app_install

- name: ensure link target
  file:
    dest: "/usr/local/bin"
    state: directory
    mode: 2775
  when: __app_install

- name: linking
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: "{{ wkhtmltox_tgz_dir }}/bin/wkhtmltopdf", dest: "/usr/local/bin/wkhtmltopdf" }
    - { src: "{{ wkhtmltox_tgz_dir }}/bin/wkhtmltoimage", dest: "/usr/local/bin/wkhtmltoimage" }
  when: __app_install

- shell: "echo {{ item }}"
  register: echo
  with_items:
    - "wkhtmltopdf version is {% if __app_current %}{{ __app_current.stdout }}{% else %}{{ wkhtmltox_tgz_version }}{% endif %}"
  changed_when: false
