---
- name: compare version with current one
  set_fact:
    __install: "{% if __current is failed %}False{% elif __current.stdout == 'NaN' %}true{% else
      %}{{ __current.stdout is version(wkhtmltox_tgz_version, '<', strict=true) }}{% endif %}"

- set_fact:
    __install: true
  when: wkhtmltox_force_purge

- name: delete existing installation
  file:
    path: "{{ wkhtmltox_tgz_dir }}"
    state: absent
  when: __install

- name: create working directory
  file:
    path: "{{ wkhtmltox_tgz_dir }}"
    mode: 0755
    state: directory
  when: __install

- name: download wkhtmltox package
  get_url:
    url: "{{ wkhtmltox_tgz_url }}"
    dest: "{{ wkhtmltox_tgz_dst }}"
  when: __install

- name: unpack tar package
  unarchive:
    src: "{{ wkhtmltox_tgz_dst }}"
    dest: "{{ wkhtmltox_tgz_dir }}"
    remote_src: true
    extra_opts: [--strip-components=1]
  when: __install

- name: apply file permissions
  file:
    dest: "{{ wkhtmltox_tgz_dir }}"
    owner: root
    group: root
    recurse: true
  when: __install

- name: clean-up
  file:
    path: "{{ wkhtmltox_tgz_dst }}"
    state: absent

- name: purge current installation packages (apt)...
  apt:
    name: "{{ wkhtmltox_dpkg_name }}"
    state: absent
    purge: true
  when: __install

- name: purge current installation packages (dpkg)...
  shell: >
    dpkg --purge {{ wkhtmltox_dpkg_name }}
  when: __install

- name: install dependencies (apt))...
  apt:
    name: [
      'ca-certificates', 'fontconfig', 'libc6', 'libfreetype6', 'libjpeg62-turbo', 'libpng16-16', 'libssl1.1',
      'libstdc++6', 'libx11-6', 'libxcb1', 'libxext6', 'libxrender1', 'xfonts-75dpi', 'xfonts-base', 'zlib1g'
    ]
    state: present
    update_cache: true
  when: __install

- name: ensure link target
  file:
    dest: "/usr/local/bin"
    state: directory
    mode: 2775
  when: __install

- name: linking
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: "{{ wkhtmltox_tgz_dir }}/bin/wkhtmltopdf", dest: "/usr/local/bin/wkhtmltopdf" }
    - { src: "{{ wkhtmltox_tgz_dir }}/bin/wkhtmltoimage", dest: "/usr/local/bin/wkhtmltoimage" }
  when: __install
