---
galaxy_info:
  author: Fatih Piristine
  description: Ansible role to compile Apache APR-Util.
  company: Hexon
  license: Apache
  min_ansible_version: 2.5
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - cloud
  - web
dependencies:
  - shared
  - apr
  - apr-iconv
